# image will be published to ghcr.io/<user>/<name>
name: Swag
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-iot
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folde
  - type: systemd
    system:
      enabled:
        - podman.socket
        - rpm-ostreed-automatic.timer
  - type: signing 

